[package]
name = "isograph_lang_parser"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
common_lang_types = { path = "../common_lang_types" }
isograph_lang_types = { path = "../isograph_lang_types" }
logos = "0.12"
thiserror = "1.0.40"
intern = { git = "https://github.com/facebook/relay.git", tag = "v16.2.0" }
graphql_lang_types = { path = "../graphql_lang_types" }
