[package]
name = "sql_schema_parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common_lang_types = { path = "../common_lang_types" }
sqlparser = { workspace = true }
prelude = { path = "../prelude" }
sql_lang_types = { path = "../sql_lang_types" }

[lints]
workspace = true
