[package]
name = "isograph_compiler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
thiserror = "1.0.40"
intern = { path = "../../relay-crates/intern" }
graphql_schema_parser = { path = "../graphql_schema_parser" }
graphql_lang_types = { path = "../graphql_lang_types" }
isograph_config = { path = "../isograph_config" }
isograph_schema = { path = "../isograph_schema" }
isograph_lang_parser = { path = "../isograph_lang_parser" }
isograph_lang_types = { path = "../isograph_lang_types" }
pico = { path = "../pico" }
pico_macros = { path = "../pico_macros" }
common_lang_types = { path = "../common_lang_types" }
graphql_artifact_generation = { path = "../graphql_artifact_generation" }
lazy_static = { workspace = true }
regex = { workspace = true }
colored = { workspace = true }
notify = { workspace = true }
tokio = { workspace = true }
notify-debouncer-full = { workspace = true }
pretty-duration = { workspace = true }
tracing = { workspace = true }
