[package]
name = "isograph_cli"
version = "0.0.4"
edition = "2021"

[dependencies]
structopt = "0.3.26"
thiserror = "1.0.40"
intern = { git = "https://github.com/facebook/relay.git" }
graphql_lang_parser = { path = "../graphql_lang_parser" }
graphql_lang_types = { path = "../graphql_lang_types" }
isograph_schema = { path = "../isograph_schema" }
isograph_lang_parser = { path = "../isograph_lang_parser" }
isograph_lang_types = { path = "../isograph_lang_types" }
common_lang_types = { path = "../common_lang_types" }
lazy_static = "1.4"
regex = "1.6.0"
colored = "2.0.4"
serde = "1.0.190"
serde_json = "1.0.108"
pathdiff = "0.2.1"
