[package]
name = "isograph_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.190"
serde_json = "1.0.108"
colorize = "0.1.0"
common_lang_types = { path = "../common_lang_types" }

