on:
  workflow_call:
    secrets:
      vs-marketplace-token:
        required: true
      open-vsx-token:
        required: true

name: Publish Isograph Extension
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Debug - Print secret values
        run: |
          echo "open-vsx-token: $(echo -n '${{ secrets.open-vsx-token }}' | base64)"
          echo "vs-marketplace-token: $(echo -n '${{ secrets.vs-marketplace-token }}' | base64)"
      - run: npm ci
        working-directory: vscode-extension
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.open-vsx-token }}
          packagePath: vscode-extension
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.vs-marketplace-token }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: vscode-extension
